In [50]:
pip install pulp

Requirement already satisfied: pulp in c:\users\ravina\anaconda\lib\site-packages (2.7.0)Note: you may need to restart the kernel to use updated packages.

In [51]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from pulp import * 
import seaborn as sns

In [52]:
df=pd.read_csv('vegan.csv')

In [53]:
df.head()

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
0,vegan,Spiked Vegan Eggnog,american,46.36,84.52,42.61
1,vegan,Vegan Cucumber Tea Sandwiches,american,41.73,143.91,73.88
2,vegan,Vegan Broccoli Soup Recipe,american,103.83,82.54,139.30
3,vegan,Baked Vegan Mac and Cheese Recipe,american,140.19,524.38,221.29
4,vegan,Vegan Nachos,american,73.05,266.38,166.64

In [54]:
df=df.drop_duplicates()

In [55]:
df.head()

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
0,vegan,Spiked Vegan Eggnog,american,46.36,84.52,42.61
1,vegan,Vegan Cucumber Tea Sandwiches,american,41.73,143.91,73.88
2,vegan,Vegan Broccoli Soup Recipe,american,103.83,82.54,139.30
3,vegan,Baked Vegan Mac and Cheese Recipe,american,140.19,524.38,221.29
4,vegan,Vegan Nachos,american,73.05,266.38,166.64

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1508 entries, 0 to 1510
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Diet_type     1508 non-null   object
 1   Recipe_name   1508 non-null   object
 2   Cuisine_type  1508 non-null   object
 3   Protein(g)    1508 non-null   float64
 4   Carbs(g)      1508 non-null   float64
 5   Fat(g)        1508 non-null   float64
dtypes: float64(3), object(3)
memory usage: 82.5+ KB

In [57]:
print(df.columns)

Index(['Diet_type', 'Recipe_name', 'Cuisine_type', 'Protein(g)', 'Carbs(g)',
       'Fat(g)'],
      dtype='object')

In [58]:
print(df.head())

  Diet_type                        Recipe_name Cuisine_type  Protein(g)  \
0     vegan                Spiked Vegan Eggnog     american       46.36
1     vegan      Vegan Cucumber Tea Sandwiches     american       41.73
2     vegan         Vegan Broccoli Soup Recipe     american      103.83
3     vegan  Baked Vegan Mac and Cheese Recipe     american      140.19
4     vegan                       Vegan Nachos     american       73.05

   Carbs(g)  Fat(g)
0     84.52   42.61
1    143.91   73.88
2     82.54  139.30
3    524.38  221.29
4    266.38  166.64

In [59]:
week_days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
split_values = np.linspace(0,len(df),8).astype(int)
split_values[-1] = split_values[-1]-1
def random_dataset():
    frac_df = df.sample(frac=1).reset_index().drop('index',axis=1)
    day_df = []
    for s in range(len(split_values)-1):
        day_df.append(frac_df.loc[split_values[s]:split_values[s+1]])
    return dict(zip(week_days,day_df))

In [60]:
df['Fat(g)']

0        42.61
1        73.88
2       139.30
3       221.29
4       166.64
         ...
1506     90.77
1507    193.42
1508    168.68
1509     60.33
1510    108.76
Name: Fat(g), Length: 1508, dtype: float64

In [61]:
df['Protein(g)']

0        46.36
1        41.73
2       103.83
3       140.19
4        73.05
         ...
1506     56.28
1507     34.40
1508     28.65
1509     44.84
1510     60.29
Name: Protein(g), Length: 1508, dtype: float64

In [62]:
random_dataset()['Monday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
0,vegan,Charred Green Beans with Mustard Vinaigrette &...,american,13.80,38.34,62.36
1,vegan,Braised Winter Vegetable Pasta,italian,59.40,297.09,35.46
2,vegan,Easy vegan burgers,american,49.36,466.88,24.18
3,vegan,Basic Chili Paste to Replace Chili Powder Recipe,american,22.16,24.70,9.29
4,vegan,End Of Summer Peach Apple Cobbler (Gluten-Free...,american,25.99,293.33,56.32
...,...,...,...,...,...,...
211,vegan,Cinnamon Sugar Vegan Donuts,american,14.41,411.22,64.83
212,vegan,Vegan Sweet Noodle Kugel,asian,83.08,340.35,162.71
213,vegan,Creamy Polenta with Tempeh Sausage and Tomatoes,american,149.12,256.35,113.00
214,vegan,Savory Tempeh Crumbles,american,43.86,24.95,34.17
215,vegan,"Gardein ""Chicken"" Scaloppini with Shiitake Sak...",asian,34.07,155.84,189.14

In [63]:
random_dataset()['Tuesday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
215,vegan,Beefless Ground Beef,american,41.35,11.42,32.61
216,vegan,Curried Lentils with Quick-Pickled Veggies,indian,225.55,590.44,50.12
217,vegan,Homemade 'Reese's Cups' Recipe,american,95.70,445.64,398.74
218,vegan,Seasoned Black-Eyed Peas,south american,16.32,101.48,30.38
219,vegan,Repair and Recover Vegan Chia Pudding recipes,british,8.47,26.41,9.87
...,...,...,...,...,...,...
426,vegan,Creamy Polenta with Tempeh Sausage and Tomatoes,american,149.12,256.35,113.00
427,vegan,Recipe: Vegan Sweet Potato Chowder,american,17.31,201.34,28.75
428,vegan,Vegan Creamy Coleslaw,american,6.76,40.99,68.13
429,vegan,Spinach & chickpea curry,indian,70.74,222.00,26.18
430,vegan,"The Happy Herbivore's Easy, Mock Tuna Salad Re...",american,102.57,315.32,37.81

In [64]:
random_dataset()['Wednesday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
430,vegan,J. Kenji López-Alt's 15-Minute Creamy (Vegan) ...,american,27.50,129.28,116.19
431,vegan,Grilled Avocado Sandwich,american,7.00,31.62,8.68
432,vegan,Curried Millet with Chickpeas and Currants,indian,43.83,222.77,55.67
433,vegan,Vegan mac 'n' cheese,american,120.58,520.01,162.10
434,vegan,Pumpkin Pie Tarts,american,121.77,431.62,291.01
...,...,...,...,...,...,...
642,vegan,Baby Bok Choy Salad with Mama O's Kimchi Paste,chinese,6.02,21.02,0.95
643,vegan,Vegan Peach Ice Scream,american,13.42,177.68,9.47
644,vegan,Classic Beans and Greens Tacos,mexican,102.35,375.30,101.68
645,vegan,Bean and Potato Vegan Enchiladas recipes,american,65.85,324.88,152.74
646,vegan,Vegan Mushroom Bolognese,american,57.26,229.43,36.96

In [65]:
random_dataset()['Thursday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
646,vegan,Vegan Cauliflower Alfredo Bake,american,114.36,389.31,28.11
647,vegan,Vegetarian Butternut Squash Chili with Black B...,american,78.55,261.64,35.03
648,vegan,Instant Pot Vegetarian Chili,american,99.51,330.95,22.49
649,vegan,ORANGE TARRAGON FRUIT LEATHER,american,10.50,71.22,25.36
650,vegan,Creamy Vegan Linguine with Wild Mushrooms recipes,american,102.78,374.81,91.03
...,...,...,...,...,...,...
857,vegan,Vegan Chocolate Dipped Strawberries,american,8.66,83.05,46.09
858,vegan,Tofu Burger,asian,122.37,445.66,80.26
859,vegan,Stir Fried Singapore Noodles with Garlic Ginge...,asian,35.17,166.07,18.47
860,vegan,Vegan Peach Ice Scream,american,13.42,177.68,9.47
861,vegan,Vegan Black Beans,american,104.19,316.86,49.68

In [66]:
random_dataset()['Friday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
861,vegan,Heirloom Tomato BLT,american,67.86,133.37,114.89
862,vegan,Vegan Chili and Cornbread Casserole,american,319.54,1159.00,291.70
863,vegan,Recipe: Best-Ever Veggie Burger,american,78.27,305.53,27.28
864,vegan,My children love beet salad!,american,21.29,95.81,50.29
865,vegan,Vegan Avocado Ceviche recipes,american,9.15,39.70,43.86
...,...,...,...,...,...,...
1073,vegan,'Clean Start': Chewy Chocolate Macaroons Recipe,french,23.58,248.33,174.13
1074,vegan,Roast asparagus bowls with tahini lemon dressing,mediterranean,38.85,152.63,26.53
1075,vegan,Vegan Potato Soup,american,79.69,262.10,130.71
1076,vegan,Cook the Book: Bengali Squash with Chickpeas,indian,19.96,116.01,49.17
1077,vegan,curried lentils with sweet potatoes.,indian,89.51,311.47,14.88

In [67]:
random_dataset()['Saturday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
1077,vegan,Avocado Pesto Pasta,italian,31.84,118.21,296.65
1078,vegan,"Homemade Baileys Irish Cream, made vegan. recipes",world,8.86,93.20,117.82
1079,vegan,"Vegan Mushroom ""Jerky"" (Slow-Roasted Mushroom ...",american,6.67,32.45,14.00
1080,vegan,Vegan Vanilla Ice Cream recipes,american,25.52,107.14,61.40
1081,vegan,Jackfruit Barbacoa Burrito Bowls,mexican,40.22,496.18,35.97
...,...,...,...,...,...,...
1288,vegan,Easy Green Chile Quesadilla Recipe With Sprout...,mexican,34.34,48.42,50.87
1289,vegan,Vegan Mayonnaise Recipe,american,9.89,4.19,341.10
1290,vegan,Creamy Vegan Avocado Potato Salad,american,26.81,185.65,60.99
1291,vegan,Braised Winter Vegetable Pasta,italian,59.40,297.09,35.46
1292,vegan,Butternut Squash and Spinach Lasagna (Vegan),italian,114.38,356.37,130.93

In [68]:
random_dataset()['Sunday']

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g)
1292,vegan,Mushroom Chia Risotto,italian,42.76,409.11,63.48
1293,vegan,Thai-Scented Asparagus Soup,south east asian,39.86,85.84,109.29
1294,vegan,Sesame parsnip & wild rice tabbouleh,middle eastern,40.07,233.50,72.60
1295,vegan,Mango Rice with Mustard,indian,18.61,178.66,51.56
1296,vegan,Smoky Charred Cauliflower and Potato Soup With...,american,38.90,228.69,31.37
...,...,...,...,...,...,...
1503,vegan,Pumpkin Tiramisu Recipe,italian,62.91,1228.60,366.25
1504,vegan,Bean and Potato Vegan Enchiladas recipes,american,65.85,324.88,152.74
1505,vegan,Vegan moussaka,american,129.49,548.31,119.91
1506,vegan,Classic Cashew Cheese,mediterranean,58.60,67.87,63.93
1507,vegan,Southwestern Crispy Fish Taco Salad,american,115.47,258.63,243.60

In [69]:
def build_nutritional_values(kg,calories):
    protein_calories = kg*4
    res_calories = calories-protein_calories
    carb_calories = calories/2.
    fat_calories = calories-carb_calories-protein_calories
    res = {'Protein Calories':protein_calories,'Carbohydrates Calories':carb_calories,'Fat Calories':fat_calories}
    return res

In [70]:
build_nutritional_values(70,2000)

{'Protein Calories': 280,
 'Carbohydrates Calories': 1000.0,
 'Fat Calories': 720.0}

In [71]:
build_nutritional_values(70,4000)

{'Protein Calories': 280,
 'Carbohydrates Calories': 2000.0,
 'Fat Calories': 1720.0}

In [72]:
def extract_gram(table):
    protein_grams = table['Protein Calories']/4.
    carbs_grams = table['Carbohydrates Calories']/4.
    fat_grams = table['Fat Calories']/9.
    res = {'Protein Grams':protein_grams, 'Carbohydrates Grams':carbs_grams,'Fat Grams':fat_grams}
    return res

In [73]:
print(build_nutritional_values(70,2500))
print(extract_gram(build_nutritional_values(70,2500)))

{'Protein Calories': 280, 'Carbohydrates Calories': 1250.0, 'Fat Calories': 970.0}
{'Protein Grams': 70.0, 'Carbohydrates Grams': 312.5, 'Fat Grams': 107.77777777777777}

In [84]:
days_data = random_dataset()
def model(day,kg,calories):
    G = extract_gram(build_nutritional_values(kg,calories))
    P = G['Protein(g) Grams']
    C = G['Carbs(g) Grams']
    F = G['Fat(g) Grams']
    day_data = days_data[day]
    day_data = day_data[day_data.calories!=0]
    food = day_data.name.tolist()
    c  = day_data.calories.tolist()
    x  = pulp.LpVariable.dicts( "x", indices = food, lowBound=0, upBound=1.5, cat='Continuous', indexStart=[] )
    e = day_data.carbohydrate.tolist()
    f = day_data.total_fat.tolist()
    p = day_data.protein.tolist()
    prob  = pulp.LpProblem( "Diet", LpMinimize )
    prob += pulp.lpSum( [x[food[i]]*c[i] for i in range(len(food))]  )
    prob += pulp.lpSum( [x[food[i]]*e[i] for i in range(len(x)) ] )>=E
    prob += pulp.lpSum( [x[food[i]]*f[i] for i in range(len(x)) ] )>=F
    prob += pulp.lpSum( [x[food[i]]*p[i] for i in range(len(x)) ] )>=P
    prob.solve()
    variables = []
    values = []
    for v in prob.variables():
        variable = v.name
        value = v.varValue
        variables.append(variable)
        values.append(value)
    values = np.array(values).round(2).astype(float)
    sol = pd.DataFrame(np.array([food,values]).T, columns = ['Food','Quantity'])
    sol['Quantity'] = sol.Quantity.astype(float)
    return sol

In [85]:
def model(prob,day,kg,calories):
    G= extract_gram(build_nutritional_values(kg,calories))
    P = G['Protein(g) Grams']
    C = G['Carbs(g) Grams']
    F = G['Fat(g) Grams']
    day_df = days_df[day]
    day_df = day_df[day_df.calories!=0]
    food = day_df.name.tolist()
    c  = day_df.calories.tolist()
    x  = pulp.LpVariable.dicts( "x", indices = food, lowBound=0, upBound=1.5, cat='Continuous', indexStart=[] )
    p = day_data.Protein(g).tolist()
    c = day_df.Carbs(g).tolist()
    f = day_data.Fat(g).tolist()
    
#    prob  = pulp.LpProblem( "Diet", LpMinimize )
    prob += pulp.lpSum( [x[food[i]]*c[i] for i in range(len(food))]  )
    prob += pulp.lpSum( [x[food[i]]*p[i] for i in range(len(x)) ] )>=P
    prob += pulp.lpSum( [x[food[i]]*c[i] for i in range(len(x)) ] )>=C
    prob += pulp.lpSum( [x[food[i]]*f[i] for i in range(len(x)) ] )>=F
    prob.solve()
    variables = []
    values = []
    for v in prob.variables():
        variable = v.name
        value = v.varValue
        variables.append(variable)
        values.append(value)
    values = np.array(values).round(2).astype(float)
    sol = pd.DataFrame(np.array([food,values]).T, columns = ['Food','Quantity'])
    sol['Quantity'] = sol.Quantity.astype(float)
    sol = sol[sol['Quantity']!=0.0]
    sol.Quantity = sol.Quantity*100
    sol = sol.rename(columns={'Quantity':'Quantity (g)'})
    return sol

In [86]:
sol_monday = model('Monday',70,1500,20)

KeyError: 'Protein(g) Grams'